// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using buyC.Data;

#nullable disable

namespace buyC.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231021191742_addNewProducts")]
    partial class addNewProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("buyC.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("buyC.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShoeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShoeId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("buyC.Models.Shoe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Shoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Man",
                            Date = new DateTime(2023, 10, 21, 19, 17, 42, 726, DateTimeKind.Utc).AddTicks(3057),
                            Description = "A comfortable and durable running shoe.",
                            Image = "https://res.cloudinary.com/dtwnppsc6/image/upload/v1697391046/Air_Jordan_Legacy_312_a46xsf.webp",
                            IsFeatured = true,
                            Name = "Air Jordan Legacy 312",
                            Price = 2799.9499999999998
                        },
                        new
                        {
                            Id = 2,
                            Category = "Man",
                            Date = new DateTime(2023, 10, 21, 19, 17, 42, 726, DateTimeKind.Utc).AddTicks(3059),
                            Description = "A stylish and comfortable casual shoe.",
                            Image = "https://res.cloudinary.com/dtwnppsc6/image/upload/v1697391046/Jumpman_MVP_vjjeul.webp",
                            IsFeatured = true,
                            Name = "Air Jordan Legacy 312",
                            Price = 3526.23
                        },
                        new
                        {
                            Id = 3,
                            Category = "Man",
                            Date = new DateTime(2023, 10, 21, 19, 17, 42, 726, DateTimeKind.Utc).AddTicks(3061),
                            Description = "A stylish and comfortable casual shoe.",
                            Image = "https://res.cloudinary.com/dtwnppsc6/image/upload/v1697391046/Jordan_Post_c5bsey.webp",
                            IsFeatured = true,
                            Name = "Air Jordan Legacy 312",
                            Price = 2300.3600000000001
                        },
                        new
                        {
                            Id = 4,
                            Category = "Man",
                            Date = new DateTime(2023, 10, 21, 19, 17, 42, 726, DateTimeKind.Utc).AddTicks(3063),
                            Description = "A stylish and comfortable casual shoe.",
                            Image = "https://res.cloudinary.com/dtwnppsc6/image/upload/v1697392428/X_PLRBOOST_SHOES_e5z4m3.avif",
                            IsFeatured = false,
                            Name = "X_PLRBOOST SHOES",
                            Price = 3499.0
                        },
                        new
                        {
                            Id = 5,
                            Category = "Man",
                            Date = new DateTime(2023, 10, 21, 19, 17, 42, 726, DateTimeKind.Utc).AddTicks(3065),
                            Description = "A stylish and comfortable casual shoe.",
                            Image = "https://res.cloudinary.com/dtwnppsc6/image/upload/v1697392428/RACER_TR23_SHOES_jpfphb.avif",
                            IsFeatured = false,
                            Name = "RACER TR23 SHOES",
                            Price = 4235.0
                        },
                        new
                        {
                            Id = 6,
                            Category = "Man",
                            Date = new DateTime(2023, 10, 21, 19, 17, 42, 726, DateTimeKind.Utc).AddTicks(3067),
                            Description = "A stylish and comfortable casual shoe.",
                            Image = "https://res.cloudinary.com/dtwnppsc6/image/upload/v1697392428/DURAMO_SL_SHOES_erzcaq.avif",
                            IsFeatured = false,
                            Name = "DURAMO SL SHOES",
                            Price = 3352.0
                        },
                        new
                        {
                            Id = 7,
                            Category = "Woman",
                            Date = new DateTime(2023, 10, 21, 19, 17, 42, 726, DateTimeKind.Utc).AddTicks(3069),
                            Description = "A stylish and comfortable casual shoe.",
                            Image = "https://res.cloudinary.com/dtwnppsc6/image/upload/v1697913855/Nano_2_Shoes_nkty64.jpg",
                            IsFeatured = false,
                            Name = "Nano 2 Shoes",
                            Price = 5242.0
                        },
                        new
                        {
                            Id = 8,
                            Category = "Woman",
                            Date = new DateTime(2023, 10, 21, 19, 17, 42, 726, DateTimeKind.Utc).AddTicks(3071),
                            Description = "A stylish and comfortable casual shoe.",
                            Image = "https://res.cloudinary.com/dtwnppsc6/image/upload/v1697913855/Nano_X3_Shoes_aiom3s.jpg",
                            IsFeatured = false,
                            Name = "Nano X3 Shoes",
                            Price = 3645.0
                        },
                        new
                        {
                            Id = 9,
                            Category = "Woman",
                            Date = new DateTime(2023, 10, 21, 19, 17, 42, 726, DateTimeKind.Utc).AddTicks(3073),
                            Description = "A stylish and comfortable casual shoe.",
                            Image = "https://res.cloudinary.com/dtwnppsc6/image/upload/v1697913855/Zig_Dynamica_4_pw2nb6.jpg",
                            IsFeatured = false,
                            Name = "Zig Dynamica 4",
                            Price = 4239.0
                        },
                        new
                        {
                            Id = 10,
                            Category = "Woman",
                            Date = new DateTime(2023, 10, 21, 19, 17, 42, 726, DateTimeKind.Utc).AddTicks(3075),
                            Description = "A stylish and comfortable casual shoe.",
                            Image = "https://res.cloudinary.com/dtwnppsc6/image/upload/v1697913855/ADIDAS_BY_STELLA_MCCARTNEY_ULTRABOOST_LIGHT_SHOES_qrnor5.avif",
                            IsFeatured = false,
                            Name = "ADIDAS BY STELLA MCCARTNEY ULTRABOOST LIGHT SHOES",
                            Price = 1989.0
                        },
                        new
                        {
                            Id = 11,
                            Category = "Kids",
                            Date = new DateTime(2023, 10, 21, 19, 17, 42, 726, DateTimeKind.Utc).AddTicks(3077),
                            Description = "A stylish and comfortable casual shoe.",
                            Image = "https://res.cloudinary.com/dtwnppsc6/image/upload/v1697914586/Club_C_Shoes_l0syzs.jpg",
                            IsFeatured = false,
                            Name = "Club C Shoes",
                            Price = 1969.0
                        },
                        new
                        {
                            Id = 12,
                            Category = "Kids",
                            Date = new DateTime(2023, 10, 21, 19, 17, 42, 726, DateTimeKind.Utc).AddTicks(3079),
                            Description = "A stylish and comfortable casual shoe.",
                            Image = "https://res.cloudinary.com/dtwnppsc6/image/upload/v1697914586/SUPERSTAR_YU-GI-OH_SHOES_ik5j5o.avif",
                            IsFeatured = false,
                            Name = "SUPERSTAR YU-GI-OH! SHOES",
                            Price = 1859.0
                        },
                        new
                        {
                            Id = 13,
                            Category = "Kids",
                            Date = new DateTime(2023, 10, 21, 19, 17, 42, 726, DateTimeKind.Utc).AddTicks(3081),
                            Description = "A stylish and comfortable casual shoe.",
                            Image = "https://res.cloudinary.com/dtwnppsc6/image/upload/v1697914587/Jordan_1_Mid_cgson8.webp",
                            IsFeatured = false,
                            Name = "Jordan 1 Mid",
                            Price = 2299.0
                        },
                        new
                        {
                            Id = 14,
                            Category = "Kids",
                            Date = new DateTime(2023, 10, 21, 19, 17, 42, 726, DateTimeKind.Utc).AddTicks(3083),
                            Description = "A stylish and comfortable casual shoe.",
                            Image = "https://res.cloudinary.com/dtwnppsc6/image/upload/v1697914587/Jumpman_Two_Trey_xft9yu.webp",
                            IsFeatured = false,
                            Name = "Jumpman Two Trey",
                            Price = 2599.0
                        },
                        new
                        {
                            Id = 15,
                            Category = "Accessories",
                            Date = new DateTime(2023, 10, 21, 19, 17, 42, 726, DateTimeKind.Utc).AddTicks(3085),
                            Description = "A stylish and comfortable casual shoe.",
                            Image = "https://res.cloudinary.com/dtwnppsc6/image/upload/v1697915415/UCL_PRO_BALL_me0fxc.avif",
                            IsFeatured = false,
                            Name = "UCL PRO BALL",
                            Price = 2299.0
                        },
                        new
                        {
                            Id = 16,
                            Category = "Accessories",
                            Date = new DateTime(2023, 10, 21, 19, 17, 42, 726, DateTimeKind.Utc).AddTicks(3087),
                            Description = "A stylish and comfortable casual shoe.",
                            Image = "https://res.cloudinary.com/dtwnppsc6/image/upload/v1697915415/TERREX_X_NATIONAL_GEOGRAPHIC_BEANIE_gg4hym.avif",
                            IsFeatured = false,
                            Name = "TERREX X NATIONAL GEOGRAPHIC BEANIE",
                            Price = 2299.0
                        },
                        new
                        {
                            Id = 17,
                            Category = "Accessories",
                            Date = new DateTime(2023, 10, 21, 19, 17, 42, 726, DateTimeKind.Utc).AddTicks(3089),
                            Description = "A stylish and comfortable casual shoe.",
                            Image = "https://res.cloudinary.com/dtwnppsc6/image/upload/v1697915415/TECH_FISHERMAN_HAT_kl0atg.avif",
                            IsFeatured = false,
                            Name = "TECH FISHERMAN HAT",
                            Price = 2299.0
                        },
                        new
                        {
                            Id = 18,
                            Category = "Accessories",
                            Date = new DateTime(2023, 10, 21, 19, 17, 42, 726, DateTimeKind.Utc).AddTicks(3091),
                            Description = "A stylish and comfortable casual shoe.",
                            Image = "https://res.cloudinary.com/dtwnppsc6/image/upload/v1697915415/MONCLER_X_ADIDAS_ORIGINALS_REVERSIBLE_BUCKET_HAT_n59ppi.avif",
                            IsFeatured = false,
                            Name = "MONCLER X ADIDAS ORIGINALS REVERSIBLE BUCKET HAT",
                            Price = 2299.0
                        });
                });

            modelBuilder.Entity("buyC.Models.Review", b =>
                {
                    b.HasOne("buyC.Models.Shoe", null)
                        .WithMany("Reviews")
                        .HasForeignKey("ShoeId");
                });

            modelBuilder.Entity("buyC.Models.Shoe", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
